### PR TITLE
Add solution for Chapter 3 Question 6-10

### PR DESCRIPTION
**Pull request by canyon289**
Ready to Merge checklist
- [x] Finish Question 6
- [x] Finish Question 7
- [x] Finish Question 8
- [x] Finish Question 9
- [x] Finish Question 10

Questions Checklist
- [x] Why [:0] for ppc values versus using all of them
- [x] Why does the logarithmic mean plot look so bad?

### CODE REVIEW

**Comment by canyon289** [comment]
Question 6 is ready for review

**Comment by aloctavodia** [comment]
I just want to add a couple of comments about Q6, in case you find them useful.

The "square" looks is due to the sampler difficulty to move to a different position in parameter space (i.e. the proposed step are mostly rejected).

To improve the sampling is enough to center the x variable. as this have the effect of de-correlate \alpha and \beta parameters.

**Comment by canyon289** [comment]
The comments are useful. Changes made

**Comment by canyon289** [comment]
Question 7 through 10 are ready for review

**Comment by aloctavodia** [comment]
* pm.sample_ppc returns an array of size samples x observed values. This makes total sense when you want to do a posterior predictive check as you want to compare the simulations/predictions be of the same size/shape as the observations to be able to do one-to-one comparison. But when you just want to make predictions at values other that the input-data that restriction does not apply. In summary I consider this a limitation of the current implementation of `sample_posterior_predictive`. Martín Loyola (one of the GSoCs candidate) has proposed to solve this problem as part of this `data container` PR.
* When you are plotting a pairs of x-y values (using lines) matplotlib (or any other ploting tool) will connect consecutive _dots_ with lines, when the plot is a line does not matter if the x-y pairs are ordered, because the _connecting lines_ will all fall on a single line, but when the plot is a curve the mess will appear! Thus you have to order the x-y pairs. Internally `plot_hpd` order the pairs.
* You may want to use a semicolon to suppress the output of the last line of a cell.

**Comment by canyon289** [comment]
Thank you for feedback. I made the changes

The part about the lines make sense, lots of overlap that you can't see :)

**Comment by aloctavodia** [comment]
I think this is ready.

**Pull request merged**
