### PR TITLE
[WIP] Chapter 2 exercises

### PR DESCRIPTION
**Pull request by canyon289**
No time expectations on this PR, especially since I have a lot of questions! Feel free to review at leisure and if it becomes a lot I can break up this PR into smaller chunkns

General comments
1. The book doesn't show a line PPC mean but the newest version of ArviZ does. Is this a concern?
2. The mean line for plot ppc looks incorrect but I could be mistaken.
3. In general, most of posteriors look similar despite the parameterization. Not sure if I made a mistake or am interpreting incorrectly.
 
Question Specific
Question 1: 
What does match those of the previous chapter refer to?

Question 5: 
I don't completely understand what the takeaway from the Prior Predictive Samples should be, all look very similar

Question 6: 
In pymc3 when generating samples from sample_posterior_predictive, how can you tell which group it came from?
https://docs.pymc.io/api/inference.html?highlight=sample_ppc

Question 7:
Other than the k parameter, and the standard deviation of sigma everything else looks basically the same

Question 8:
Same as question 7, models look roughly the same. Hard to come up with a good takeaway

Question 9:
Should python-graphviz be added to envfile?

### CODE REVIEW

**Comment by aloctavodia** [comment]
Sorry for the delay @canyon289 and thanks again!

Here I have some answers to your questions.

General comments

1. I can not remember why I set `mean=False`. ¿? ¿? ¿?

2. I think the mean line is correct (but I understand your concern), it look very flat when you use a student T (with low value of nu) because this distribution have really long tails, thus the chance of finding a sample far away from the bulk is high.


Question Specific
Question 1:
I am referring to the beta-binomial model and it's 3 priors. In my Spanish course some students decide to redo figure 1.5 using PyMC3, this is of course not necessary, but it looks nice, haha.


Question 5:
In terms of the mean value, all models are very similar, the greatest different is in how much weight you put on the tails of the distribution. Also if the ppc is done per group the differences will be larger.

Question 6:
Unfortunately PyMC3 does not offer a direct way. You have to _manually_ extract the proper values using the `idx` variable. In fact One student last tear offer to send a PR to fix this. I should contact him and ask if he is still interested.

Question 7:
I think a forestplot is better here than a ppc plot

If the groups are the same for example when G_samples = [18, 18, 18]  (or [3, 3, 3]) the estimation of theta should be the same, for a hierarchical or non-hierarchical model, although the concentration parameter (or standard deviation) should be different as in a non-hierarchical model you have separated groups and in a hierarchical model you have partially pooled groups (or in other words more data to estimate parameters). 

If the group are different like G_samples = [18, 3, 3], then the hierarchical and non-hierarchical model will provide different value of theta as the hierarchical model provides a weighted average value of the groups.



Question 8:
I think a forestplot is a good option here. In this example the means are pretty similar but the uncertainty should be lower for the hierarchical model.


Question 9:
I think you are right!


Additional comment
* While it is true that "string variable names do not have to the same as the object name" we used to recommend using the same name. But we also used to recommend using `find_MAP()` haha.

**Comment by canyon289** [comment]
This comment is a running task list of things needed to close out chapter 2
- [x] Add Beta Binomial model from chapter 1
- [x] Compare groups for Q6 tips dataset
- [x] Finish question 7
- [ ] Compare grouped and pooled hierarchical model
- [x] Add GraphViz to environment file

**Comment by canyon289** [comment]
I have a couple questions remaining

For question 7, I tried forestplot for individual, and hierarchical models, but I still don't see a big difference in either `az.summary` or forestplots. Am I making a mistake somewhere?

For Plot PPC I don't understand what the mean line represents, it doesn't really look like the mean of all the brown lines, should it be "in the middle" of them?

image

**Comment by canyon289** [comment]
@aloctavodia 

I updated Question 6 (Groups comparison in tips) Let me know if this one is good.

Besides that one I think the only thing left is my confusion on Chapter 7.

**Comment by aloctavodia** [comment]
I guess the problem with the mean is related to the different number of samples, the density of mean is estimated with a lot of samples and is thus closer to the true distributions while the density of the individual samples is a worst estimation, the KDE is estimating a broader density (and thus a less tall one). I will test if this is truly the case, and I will send you a code-example. BTW, I don't think this is a problem with our particular implementation of the KDE, anyway if this is the problem I will try to think about a solution.

**Comment by canyon289** [comment]
Just it be clear I'm not suggesting anything is wrong! Just trying to
understand. We can move this discussion to another thread as it's
independent from the homework solutions.

**Comment by aloctavodia** [comment]
You are very clear, we should continue the kde/ppc discussion on ArviZ's slack, I will try to send you the code-example ASAP. Do you think this is ready to merge?

**Comment by canyon289** [comment]
I think this is ready to merge if you do.

**Pull request merged**
