### PR TITLE
Add Chapter 4 Exercises 1-5

### PR DESCRIPTION
**Pull request by canyon289**
- [ ] Exercise 1
- [ ] Exercise 2
- [ ] Exercise 3
- [ ] Exercise 4
- [ ] Exercise 5

Questions
- [ ] For Exercise 2 does the weakly informative prior pertain to both alpha and beta or just one?

### CODE REVIEW

**Comment by aloctavodia** [comment]
both

**Comment by aloctavodia** [comment]
A4 and A5, please elaborate.

**Comment by canyon289** [comment]
Ready for review again

**Comment by aloctavodia** [comment]
LGTM! Except for a few typos.

**Comment by canyon289** [comment]
Shoot, I'll read through for typos

**Pull request merged**
