### PR TITLE
NB extending multinomial regression with prior/post predictive checks

### PR DESCRIPTION
**Pull request by AlexAndorra**
As discussed, here is a NB extending the multinomial regression example of chapter 4. The goal is to show how to do prior and posterior predictive checks with these not-so-simple types of models. 
I tried to explicit the whole modeling workflow, hoping that would be helpful to people 😉 

Of course, don't hesitate to correct any mistake or add any useful aspect - most notably with ArviZ, as you've got a better view than me on the API.

Live long & PyMCheers 🖖 

_PS: I generated the last cell with [the watermark package](https://github.com/rasbt/watermark), so it won't run with the current environment on the repo. As it's not critical, I didn't add it to the yml file, but I can do it if you want_

### CODE REVIEW

**Comment by aloctavodia** [comment]
This is great! Thanks a lot! A few minor comments

* a typo. The sentence "The idea is to plot predictions against observed data, to see if the model correctly approximated". Should be "The idea is to plot predictions against observed data, to see if the model correctly approximates"

* you do a ppc plot for a categorical distribution (a discrete distribution) and represent it with a KDE (that assumes a continuous distribution). I think this is fine as long as you add a short note point out to this detail. 

* feel free to add the watermark package to the yml

**Comment by AlexAndorra** [comment]
Glad you like it ;)
My answers:

- Done
- You're right, I'll add a note. Actually, is there an option in `az.plot_ppc` for these cases?
- Done

**Comment by aloctavodia** [comment]
You can try with the `kind` argument. Valid values are "density" (default), "cumulative", or "scatter"

**Comment by AlexAndorra** [comment]
Ah yeah, I tried that but found the plot with KDE was clearer.
All updates are now done and pushed ;)

**Comment by aloctavodia** [comment]
Thanks @AlexAndorra!

**Pull request merged**
