### PR TITLE
Add Ch3 Q1-Q5

### PR DESCRIPTION
**Pull request by canyon289**
Completed Q1 and Q2 solutions at time of writing

Resolve following comments

- [ ]  y_i are observations, the posterior is explicitly represented in the model specification is just a consequence of it.
- [x] In would say the posterior have tree parameters/dimensions \alpha, \beta and \epsilon, \mu is just something we can compute from the posterior (this generally generates debates in my classes).
- [x] Instead of writing abs(pm.Normal("sd", 0, 25)) you should write pm.HalfNormal("sd", 25), the sd should not be bimodal.

### CODE REVIEW

**Comment by canyon289** [comment]
Ready for review. I'll finish the remaining questions separate PRs with around ~4 questions each

**Comment by aloctavodia** [comment]
A few comments.

1. y_i are observations, the posterior is explicitly represented in the model specification is just a consequence of it.
4. In would say the posterior have tree parameters/dimensions \alpha, \beta and \epsilon, \mu is just something we can compute from the posterior (this generally generates debates in my classes).
5. Instead of writing abs(pm.Normal("sd", 0, 25)) you should write pm.HalfNormal("sd", 25), the sd should not be bimodal.

**Comment by canyon289** [comment]
Just to be sure I understand

1. What would the posterior be in Exercise 1? \mu and \sigma?
3. Since |Normal(0,25)| is written as `pm.HalfNormal("sd", 0, 25)` in code why not just write HalfNormal(0,25) in math equations?

**Comment by aloctavodia** [comment]
1. The posterior will be distribution over mu and sigma, but the posterior is not directly specified in the model.
2. You can write it both ways, you will find both expressions in the literature.

**Comment by canyon289** [comment]
Thanks! I'll look through to make sure everything is good and then will merge.

Much appreciated

**Pull request merged**
