### PR TITLE
Chapter 3 Part 3

### PR DESCRIPTION
**Pull request by canyon289**
Exercise Completion
- [ ]  Question 11
- [ ]  Question 12
- [ ]  Question 13
- [ ]  Question 14
- [ ]  Question 15
- [ ]  Question 16
- [ ]  Question 17

Questions
- [ ]  For Exercise 11 is one model supposed to be used for quartets 1-3
- [ ]  Is implementation of quartet 4 correct?
- [ ] What is does alpha temp do in model_mlr?

### CODE REVIEW

**Comment by canyon289** [comment]
All of chapter 3 is now pushed and in PR form!

**Comment by aloctavodia** [comment]
q11. 
* It meas a single model for the 3 datasets
* The 4 anscombe datasets are distributed with the notebooks (see data/anscombe.csv)
* The idea is just to try model, so your model makes sense. Another model, that will be probably easier to fit is to model two groups conditional on the known value of x. something like.

with pm.Model() as anscombe:
    mu = pm.HalfNormal("mu", sd=10, shape=2)
    sd = pm.HalfNormal("sd", sd=10)

    y = pm.Normal("y", mu=mu[idx], sd=sd, observed=df["y4"].values)

where idx is an dummy variable telling the model if x== 8 or x==19

q14 Instead of using az.plot_hpd you may want to plot the lines, otherwise you will not see the uncertainty for the last group.

q15 if you center the data the value (and meaning) of α will be different compared to the uncentered data.  α_tmp is α' in eq 3.5

**Comment by aloctavodia** [comment]
Is this ready? (just asking not trying to be pushy, haha)

**Comment by canyon289** [comment]
I missed the comments :( I need to go through and implement. Sorry for the delay

**Comment by canyon289** [comment]
I made the updates finally

**Comment by canyon289** [comment]
For exercise 12 I do not know what `model_t2` is

**Comment by aloctavodia** [comment]
`model_t2` is in the notebook

**Comment by canyon289** [comment]
I don't know how I missed that. Apologies

**Comment by canyon289** [comment]
@aloctavodia i made all changes. No rush on review

**Comment by aloctavodia** [comment]
LGTM!

**Comment by canyon289** [comment]
Awesome. Merging. Will make a consolidation PR for the split up chapters this weekend

**Pull request merged**
